# Python Data Cleaning Project
This project using Python in Jupyter Notebooks showcases my data cleaning abilities in Python using Pandas.

## Step 1: Imports

In [2]:
import pandas as pd
url = "https://raw.githubusercontent.com/Ethan-Mitchell-Data-Analyst/Python-Data-Cleaning-Project/main/data/Messy_Employee_dataset.csv"
df = pd.read_csv(url)

print(df.head())
print(df.info())

  Employee_ID First_Name Last_Name   Age   Department_Region    Status  \
0     EMP1000        Bob     Davis  25.0   DevOps-California    Active
1     EMP1001        Bob     Brown   NaN       Finance-Texas    Active
2     EMP1002      Alice     Jones   NaN        Admin-Nevada   Pending
3     EMP1003        Eva     Davis  25.0        Admin-Nevada  Inactive
4     EMP1004      Frank  Williams  25.0  Cloud Tech-Florida    Active

    Join_Date     Salary                       Email       Phone  \
0    4/2/2021   59767.65       bob.davis@example.com -1651623197
1   7/10/2020   65304.66       bob.brown@example.com -1898471390
2   12/7/2023   88145.90     alice.jones@example.com -5596363211
3  11/27/2021   69450.99       eva.davis@example.com -3476490784
4    1/5/2022  109324.61  frank.williams@example.com -1586734256

  Performance_Score  Remote_Work
0           Average         True
1         Excellent         True
2              Good         True
3              Good         True
4              Poor        False
<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   str
 1   First_Name         1020 non-null   str
 2   Last_Name          1020 non-null   str
 3   Age                809 non-null    float64
 4   Department_Region  1020 non-null   str
 5   Status             1020 non-null   str
 6   Join_Date          1020 non-null   str
 7   Salary             996 non-null    float64
 8   Email              1020 non-null   str
 9   Phone              1020 non-null   int64
 10  Performance_Score  1020 non-null   str
 11  Remote_Work        1020 non-null   bool
dtypes: bool(1), float64(2), int64(1), str(8)
memory usage: 88.8 KB
None

## Step 2: Business Scenario and Initial understanding of dataset 

Business Scenario: Provide a well-formatted list of employees [...] for others to group data as they need (e.g. combinations of Department and Region).

The dataset link on Kaggle already details some of the inconsistency in the dataset.

## Step 3: Data Cleaning

- [x] Drop duplicates (drop rows we don't need)
- [ ] Drop columns we don't need (for now I want to keep all the columns)
- [x] Strip non-alphabet characters/non-numbers for each column as relevant
- [x] Split Department_Region column into Department and Region
- [x] Convert Join_Date strings to datetime format
- [x] Change Salary column to include US$ in the column name
- [x] Format Phone column for making international calls
- [x] Check unique values in Status, Performance_Score and Remote_Work columns - there shouldn't be any typos
- [ ] Re-index Department and Region columns
- [ ] Remove Department_Region compound column, now useless

In [3]:
#Drop duplicates
df = df.drop_duplicates()

In [4]:
#Strip non-alphabet characters/non-numbers for each column as relevant
df["Employee_ID"] = df["Employee_ID"].str.replace('^a-zA-Z0-9', '')
df["First_Name"] = df["First_Name"].str.replace('^a-zA-Z', '')
df["Last_Name"] = df["Last_Name"].str.replace('^a-zA-Z', '')
df["Department_Region"] = df["Department_Region"].str.replace('^a-zA-Z-', '')
df["Status"] = df["Status"].str.replace('^a-zA-Z', '')
df["Join_Date"] = df["Join_Date"].str.replace('^0-9/', '')
df["Performance_Score"] = df["Performance_Score"].str.replace('^a-zA-Z', '')

In [5]:
#Split Department_Region column into Department and Region
df[["Department", "Region"]] = df["Department_Region"].str.split('-', expand=True)
#df

In [6]:
#Convert Join_Date strings to datetime format
df["Join_Date"] = pd.to_datetime(df["Join_Date"])
df["Join_Date"]

0      2021-04-02
1      2020-07-10
2      2023-12-07
3      2021-11-27
4      2022-01-05
          ...
1015   2023-08-19
1016   2021-11-07
1017   2023-10-04
1018   2024-12-16
1019   2021-02-22
Name: Join_Date, Length: 1020, dtype: datetime64[us]

In [7]:
#Change Salary column to include US$ in the column name
df.rename(columns={'Salary': 'Salary_US$'})

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary_US$,Email,Phone,Performance_Score,Remote_Work,Department,Region
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,2021-04-02,59767.65,bob.davis@example.com,-1651623197,Average,True,DevOps,California
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,2020-07-10,65304.66,bob.brown@example.com,-1898471390,Excellent,True,Finance,Texas
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,2023-12-07,88145.90,alice.jones@example.com,-5596363211,Good,True,Admin,Nevada
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,2021-11-27,69450.99,eva.davis@example.com,-3476490784,Good,True,Admin,Nevada
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,2022-01-05,109324.61,frank.williams@example.com,-1586734256,Poor,False,Cloud Tech,Florida
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,EMP2015,David,Miller,30.0,HR-California,Active,2023-08-19,NaN,david.miller@example.com,-3546212759,Good,True,HR,California
1016,EMP2016,David,Johnson,30.0,Cloud Tech-Texas,Inactive,2021-11-07,100215.06,david.johnson@example.com,-2508261122,Good,True,Cloud Tech,Texas
1017,EMP2017,Charlie,Williams,40.0,Finance-New York,Active,2023-10-04,114587.11,charlie.williams@example.com,-1261632487,Average,False,Finance,New York
1018,EMP2018,Alice,Garcia,30.0,HR-Florida,Inactive,2024-12-16,71318.79,alice.garcia@example.com,-8995729892,Good,True,HR,Florida
1019,EMP2019,Heidi,Jones,30.0,DevOps-Illinois,Pending,2021-02-22,77764.24,heidi.jones@example.com,-7629745492,Average,False,DevOps,Illinois

In [8]:
#Format Phone column for making international calls, i.e. +1 (xxx) xxx-xxxx, this requires string parsing
df["Phone"] = df["Phone"].map(str).str.strip("-")
df["Phone"].str.replace('^0-9', '')

0       1651623197
1       1898471390
2       5596363211
3       3476490784
4       1586734256
           ...
1015    3546212759
1016    2508261122
1017    1261632487
1018    8995729892
1019    7629745492
Name: Phone, Length: 1020, dtype: str

In [9]:
df["Phone"] = df["Phone"].apply(lambda x: "+1 (" + x[0:3] + ") " + x[3:6] + "-" + x[6:10])
df["Phone"]

0       +1 (165) 162-3197
1       +1 (189) 847-1390
2       +1 (559) 636-3211
3       +1 (347) 649-0784
4       +1 (158) 673-4256
              ...
1015    +1 (354) 621-2759
1016    +1 (250) 826-1122
1017    +1 (126) 163-2487
1018    +1 (899) 572-9892
1019    +1 (762) 974-5492
Name: Phone, Length: 1020, dtype: str

In [10]:
#Check unique values in Status, Performance_Score and Remote_Work columns - there shouldn't be any typos
print(df["Status"].unique())
print(df["Performance_Score"].unique())
print(df["Remote_Work"].unique())

<StringArray>
['Active', 'Pending', 'Inactive']
Length: 3, dtype: str
<StringArray>
['Average', 'Excellent', 'Good', 'Poor']
Length: 4, dtype: str
[ True False]

In [11]:
#Checking everything has worked
df

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work,Department,Region
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,2021-04-02,59767.65,bob.davis@example.com,+1 (165) 162-3197,Average,True,DevOps,California
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,2020-07-10,65304.66,bob.brown@example.com,+1 (189) 847-1390,Excellent,True,Finance,Texas
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,2023-12-07,88145.90,alice.jones@example.com,+1 (559) 636-3211,Good,True,Admin,Nevada
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,2021-11-27,69450.99,eva.davis@example.com,+1 (347) 649-0784,Good,True,Admin,Nevada
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,2022-01-05,109324.61,frank.williams@example.com,+1 (158) 673-4256,Poor,False,Cloud Tech,Florida
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,EMP2015,David,Miller,30.0,HR-California,Active,2023-08-19,NaN,david.miller@example.com,+1 (354) 621-2759,Good,True,HR,California
1016,EMP2016,David,Johnson,30.0,Cloud Tech-Texas,Inactive,2021-11-07,100215.06,david.johnson@example.com,+1 (250) 826-1122,Good,True,Cloud Tech,Texas
1017,EMP2017,Charlie,Williams,40.0,Finance-New York,Active,2023-10-04,114587.11,charlie.williams@example.com,+1 (126) 163-2487,Average,False,Finance,New York
1018,EMP2018,Alice,Garcia,30.0,HR-Florida,Inactive,2024-12-16,71318.79,alice.garcia@example.com,+1 (899) 572-9892,Good,True,HR,Florida
1019,EMP2019,Heidi,Jones,30.0,DevOps-Illinois,Pending,2021-02-22,77764.24,heidi.jones@example.com,+1 (762) 974-5492,Average,False,DevOps,Illinois

## Step 4: Export as CSV

In [12]:
df.to_csv("Cleaned-Messy-Employee-Dataset.csv", index=False)