# Python Data Cleaning Project
This project using Python in Jupyter Notebooks showcases my data cleaning abilities in Python using Pandas.

## Step 1: Imports
This step ensures my CSV file is imported correctly and can be read in my project.

In [ ]:
#for GitHub - use Kaggle dataset instead of local file path

import pandas as pd
df = pd.read_csv("/Users/ethanm/Desktop/Python-data-cleaning-project/data/Messy_Employee_dataset.csv")
print(df.head())
print(df.info())

  Employee_ID First_Name Last_Name   Age   Department_Region    Status  \
0     EMP1000        Bob     Davis  25.0   DevOps-California    Active
1     EMP1001        Bob     Brown   NaN       Finance-Texas    Active
2     EMP1002      Alice     Jones   NaN        Admin-Nevada   Pending
3     EMP1003        Eva     Davis  25.0        Admin-Nevada  Inactive
4     EMP1004      Frank  Williams  25.0  Cloud Tech-Florida    Active

    Join_Date     Salary                       Email       Phone  \
0    4/2/2021   59767.65       bob.davis@example.com -1651623197
1   7/10/2020   65304.66       bob.brown@example.com -1898471390
2   12/7/2023   88145.90     alice.jones@example.com -5596363211
3  11/27/2021   69450.99       eva.davis@example.com -3476490784
4    1/5/2022  109324.61  frank.williams@example.com -1586734256

  Performance_Score  Remote_Work
0           Average         True
1         Excellent         True
2              Good         True
3              Good         True
4              Poor        False
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   object
 1   First_Name         1020 non-null   object
 2   Last_Name          1020 non-null   object
 3   Age                809 non-null    float64
 4   Department_Region  1020 non-null   object
 5   Status             1020 non-null   object
 6   Join_Date          1020 non-null   object
 7   Salary             996 non-null    float64
 8   Email              1020 non-null   object
 9   Phone              1020 non-null   int64
 10  Performance_Score  1020 non-null   object
 11  Remote_Work        1020 non-null   bool
dtypes: bool(1), float64(2), int64(1), object(8)
memory usage: 88.8+ KB
None

## Step 2: Initial understanding of dataset 
There are null values in the Age and Salary columns, which are the **quantitative** data entries for this dataset. I should treat these null values in accordance with the business requirements for this piece of analysis.
Depending on the reason for analysis, the data cleaning process could either:
- leave these values as they are
- impute the mean or median
- remove all rows containing nulls

## Step 3: Data Cleaning

- [x] Drop duplicates (drop rows we don't need)
- [x] Drop columns we don't need (for now I want to keep all the columns)
- [x] Split Department_Region column into Department and Region
- [x] Format Phone column for making international calls, i.e. +1 (xxx) xxx-xxxx, this requires string parsing
- [ ] Check what we can't see (e.g. employee_ID is formatted correctly) - strip non-alphabet characters/non-numbers for each column as relevant 
- N.B.: .str.replace('[^a-zA-Z0-9]', '') will replace everything that's NOT in that list (the ^ = not) with nothing

In [33]:
df = df.drop_duplicates()
df

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1015,EMP2015,David,Miller,30.0,HR-California,Active,8/19/2023,NaN,david.miller@example.com,-3546212759,Good,True
1016,EMP2016,David,Johnson,30.0,Cloud Tech-Texas,Inactive,11/7/2021,100215.06,david.johnson@example.com,-2508261122,Good,True
1017,EMP2017,Charlie,Williams,40.0,Finance-New York,Active,10/4/2023,114587.11,charlie.williams@example.com,-1261632487,Average,False
1018,EMP2018,Alice,Garcia,30.0,HR-Florida,Inactive,12/16/2024,71318.79,alice.garcia@example.com,-8995729892,Good,True
1019,EMP2019,Heidi,Jones,30.0,DevOps-Illinois,Pending,2/22/2021,77764.24,heidi.jones@example.com,-7629745492,Average,False

Getting rid of characters we don't want - column by column

In [ ]:
#Employee_ID
#df["Employee_ID"] = df["Employee_ID"].str.replace('^a-zA-Z-0-9', '')

In [ ]:
#First_Name
#df["First_Name"] = df["First_Name"].str.replace('^a-zA-Z', '')

#Last_Name
#df["Last_Name"] = df["Last_Name"].str.replace('^a-zA-Z', '')

#Age - doesn't need anything, it's already a float column

#Department_Region -> we need to find out if there are any special characters in this column other than the hyphen

AttributeError: Can only use .str accessor with string values!

In [ ]:
#df[["Department", "Region"]] = df["Department_Region"].str.split('-', expand=True)
#df
#This creates new columns at the end of the dataframe called Department and Region.

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work,Department,Region
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True,DevOps,California
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True,Finance,Texas
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True,Admin,Nevada
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True,Admin,Nevada
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False,Cloud Tech,Florida
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,EMP2015,David,Miller,30.0,HR-California,Active,8/19/2023,NaN,david.miller@example.com,-3546212759,Good,True,HR,California
1016,EMP2016,David,Johnson,30.0,Cloud Tech-Texas,Inactive,11/7/2021,100215.06,david.johnson@example.com,-2508261122,Good,True,Cloud Tech,Texas
1017,EMP2017,Charlie,Williams,40.0,Finance-New York,Active,10/4/2023,114587.11,charlie.williams@example.com,-1261632487,Average,False,Finance,New York
1018,EMP2018,Alice,Garcia,30.0,HR-Florida,Inactive,12/16/2024,71318.79,alice.garcia@example.com,-8995729892,Good,True,HR,Florida
1019,EMP2019,Heidi,Jones,30.0,DevOps-Illinois,Pending,2/22/2021,77764.24,heidi.jones@example.com,-7629745492,Average,False,DevOps,Illinois

# DO NOT RUN THE CELL BELOW!

In [ ]:
#df["Phone"] = df["Phone"].map(str).str.strip("-")
#df
#from here, get rid of any characters that are not 1-9


#String Parsing
#df["Phone"] = df["Phone"].apply(lambda x: "+1 (" + x[0:3] + ") " + x[3:6] + "-" + x[6:10])
#df["Phone"]

0       +1 (165) 162-3197
1       +1 (189) 847-1390
2       +1 (559) 636-3211
3       +1 (347) 649-0784
4       +1 (158) 673-4256
              ...
1015    +1 (354) 621-2759
1016    +1 (250) 826-1122
1017    +1 (126) 163-2487
1018    +1 (899) 572-9892
1019    +1 (762) 974-5492
Name: Phone, Length: 1020, dtype: object

## Step 4: Check everything